// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import React from "react";
import Banner from "/Users/HP/Documents/Test-Valley-Project/my-nextjs-app/components/Banner"; // Adjust the file path as needed
import Shortcut from "/Users/HP/Documents/Test-Valley-Project/my-nextjs-app/components/Shortcut"; // Adjust the file path as needed
import ProductTile from "/Users/HP/Documents/Test-Valley-Project/my-nextjs-app/components/ProductTile"; // Adjust the file path as needed
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Example usage of imported components */}
        <Banner imageUrl="banner-url" title="Banner Title" discount={10} price="$100" rating={4.5} />
        <Shortcut title="Shortcut Title" url="shortcut-url" />
        <ProductTile
          imageUrl="product-image-url"
          title="Product Title"
          discount={20}
          price="$80"
          rating={4.7}
          details="Product details"
        />
        {children}
      </body>
    </html>
  );
}
